---
- hosts: 10.20.1.146
  become: True
  tasks:
    - name: Install Apache Server
      yum:
        name: httpd
        state: present
    - name: Enable Apache on System Reboot
      service:
        name: httpd
        enabled: true
    - name: Install Git
      yum:
         name: git 
         state: present
    - name: Deploy Website from Git
      git:
        repo: https://github.com/quickbooks2018/learning-ansible.git
        dest: /var/www/html
    - name: Restart Apache Server
      service:
        name: httpd
        state: restarted    
                        
